general{
  operation_mode: MODE_TEST
  robot_type: ROBOT_TYPE_MANIPULATOR_ARM
  name: "camera_test"
  id: 1
}

robot {
  perceptions {
    single_perceptions {
      node {
        id: 1
        node_type: CAMERA_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: IMAGE
          topic: "camera_1"
          publish_rate_hz: 30
        }
      }
      sensor {
        sensor_name: "webcam"
        id: 1
        sensor_type: IMAGE
        opencv_config {
          id: 0
          width: 640
          height: 480
          fps: 30
        }
      }
    }
  }
}
