# TODO(hmoon): Update perception layer with the board too.
general{
  operation_mode: MODE_TELEOPERATE
  robot_type: ROBOT_TYPE_MANIPULATOR_ARM
  name: "so100"
  id: 1
}
robot {
  boards {
    name: "arm_bus"
    board_type: FEETECH_BUS
    comm {
      comm_type: SERIAL
      transport_type: MESSAGE
      serial_config { port: "/dev/ttyACM0" baudrate: 1000000 }
    }

  channels { index: 1 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 1 } }
  channels { index: 2 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 2 } }
  channels { index: 3 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 3 } }
  channels { index: 4 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 4 } }
  channels { index: 5 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 5 } }
  channels { index: 6 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 6 } }
  }

  perceptions {
    single_perceptions {
      node {
        id: 1
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_1_state"
          publish_rate_hz: 30
        }
      }
      sensor {
        sensor_name: "sts3215_encoder_1"
        id: 1
        sensor_type: POSITION
        operational_lower_limit: 1147
        operational_upper_limit: 3154
        board_name: "arm_bus"
        channel: 1
      }
    }
    single_perceptions {
      node {
        id: 1
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_2_state"
          publish_rate_hz: 30
        }
      }
      sensor {
        sensor_name: "sts3215_encoder_2"
        id: 2
        sensor_type: POSITION
        operational_lower_limit: 1670
        operational_upper_limit: 3986
        board_name: "arm_bus"
        channel: 2
      }
    }
    single_perceptions {
      node {
        id: 1
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_3_state"
          publish_rate_hz: 30
        }
      }
      sensor {
        sensor_name: "sts3215_encoder_3"
        id: 3
        sensor_type: POSITION
        operational_lower_limit: 910
        operational_upper_limit: 3113
        board_name: "arm_bus"
        channel: 3
      }
    }
    single_perceptions {
      node {
        id: 1
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_4_state"
          publish_rate_hz: 30
        }
      }
      sensor {
        sensor_name: "sts3215_encoder_4"
        id: 4
        sensor_type: POSITION
        operational_lower_limit: 0
        operational_upper_limit: 2407
        board_name: "arm_bus"
        channel: 4
      }
    }
    single_perceptions {
      node {
        id: 1
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_5_state"
          publish_rate_hz: 30
        }
      }
      sensor {
        sensor_name: "sts3215_encoder_5"
        id: 5
        sensor_type: POSITION
        operational_lower_limit: 1730
        operational_upper_limit: 3811
        board_name: "arm_bus"
        channel: 5
      }
    }
    single_perceptions {
      node {
        id: 1
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_6_state"
          publish_rate_hz: 30
        }
      }
      sensor {
        sensor_name: "sts3215_encoder_6"
        id: 6
        sensor_type: POSITION
        operational_lower_limit: 2028
        operational_upper_limit: 3100
        board_name: "arm_bus"
        channel: 6
      }
    }
  }
}
