general{
  operation_mode: MODE_INFERENCE
  robot_type: ROBOT_TYPE_MANIPULATOR_ARM
  name: "so100"
  id: 1
}
robot {
  boards {
    name: "arm_bus"
    board_type: FEETECH_BUS
    comm {
      comm_type: SERIAL
      transport_type: MESSAGE
      serial_config { port: "/dev/ttyACM0" baudrate: 1000000 }
    }
    channels { index: 1 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 1 } }
    channels { index: 2 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 2 } }
    channels { index: 3 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 3 } }
    channels { index: 4 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 4 } }
    channels { index: 5 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 5 } }
    channels { index: 6 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 6 } }
  }
  actions {
    single_actions {
      node {
        id: 1
        node_type: ACTUATOR_SUBSCRIBER
        qos_setting {}
        subscriptions {
          ros2_data_type: FLOAT32
          topic: "sts_motor_1/position"
          normalized: false
        }
      }
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts_motor_1"
        id: 1
        motor_type: MOTOR_STS3215
        board_name: "arm_bus"
        channel: 1
        physical_lower_limit: 0
               physical_upper_limit: 4095
        operational_lower_limit: 973
        operational_upper_limit: 3034
        sts3215_config {
          servo_id: 1
          move_speed: 500
          idle_position: 2070
        }
      }
    }
    single_actions {
      node {
        id: 1
        node_type: ACTUATOR_SUBSCRIBER
        qos_setting {}
        subscriptions {
          ros2_data_type: FLOAT32
          topic: "sts_motor_2/position"
          normalized: false
        }
      }
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts_motor_2"
        id: 2
        motor_type: MOTOR_STS3215
        board_name: "arm_bus"
        channel: 2
        physical_lower_limit: 0
               physical_upper_limit: 4095
        operational_lower_limit: 858
        operational_upper_limit: 3154
        sts3215_config {
          servo_id: 2
          move_speed: 500
          idle_position: 847
        }
      }
    }
    single_actions {
      node {
        id: 1
        node_type: ACTUATOR_SUBSCRIBER
        qos_setting {}
        subscriptions {
          ros2_data_type: FLOAT32
          topic: "sts_motor_3/position"
          normalized: false
        }
      }
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts_motor_3"
        id: 3
        motor_type: MOTOR_STS3215
        board_name: "arm_bus"
        channel: 3
        physical_lower_limit: 0
                physical_upper_limit: 4095
        operational_lower_limit: 798
        operational_upper_limit: 3015
        sts3215_config {
          servo_id: 3
          move_speed: 500
          idle_position: 3011
        }
      }
    }
    single_actions {
      node {
        id: 1
        node_type: ACTUATOR_SUBSCRIBER
        qos_setting {}
        subscriptions {
          ros2_data_type: FLOAT32
          topic: "sts_motor_4/position"
          normalized: false
        }
      }
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts_motor_4"
        id: 4
        motor_type: MOTOR_STS3215
        board_name: "arm_bus"
        channel: 4
        physical_lower_limit: 0
               physical_upper_limit: 4095
        operational_lower_limit: 668
        operational_upper_limit: 3124
        sts3215_config {
          servo_id: 4
          move_speed: 500
          idle_position: 655
        }
      }
    }
    single_actions {
      node {
        id: 1
        node_type: ACTUATOR_SUBSCRIBER
        qos_setting {}
        subscriptions {
          ros2_data_type: FLOAT32
          topic: "sts_motor_5/position"
          normalized: false
        }
      }
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts_motor_5"
        id: 5
        motor_type: MOTOR_STS3215
        board_name: "arm_bus"
        channel: 5
        physical_lower_limit: 0
               physical_upper_limit: 4095
        operational_lower_limit: 902
        operational_upper_limit: 2955
        sts3215_config {
          servo_id: 5
          move_speed: 1000
          idle_position: 1838
        }
      }
    }
    single_actions {
      node {
        id: 1
        node_type: ACTUATOR_SUBSCRIBER
        qos_setting {}
        subscriptions {
          ros2_data_type: FLOAT32
          topic: "sts_motor_6/position"
          normalized: false
        }
      }
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts_motor_6"
        id: 6
        motor_type: MOTOR_STS3215
        board_name: "arm_bus"
        channel: 6
        physical_lower_limit: 0
               physical_upper_limit: 4095
        operational_lower_limit: 1795
        operational_upper_limit: 3235
        sts3215_config {
          servo_id: 6
          move_speed: 1000
          idle_position: 1806
        }
      }
    }
  }

  perceptions {
    single_perceptions {
      node {
        id: 2
        node_type: CAMERA_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: IMAGE
          topic: "camera_1"
          publish_rate_hz: 30
        }
      }
      perception_type: CAMERA
      camera {
        camera_name: "webcam"
        id: 1
        camera_type: OPENCV
        comm{}
        opencv_config {
          id: 0
          width: 640
          height: 480
          fps: 30
        }
      }
    }
    single_perceptions {
      node {
        id: 3
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_1_state"
          publish_rate_hz: 30
        }
      }
      sensor {
        sensor_name: "sts3215_encoder_1"
        id: 1
        sensor_type: JOINT_POSITION
        operational_lower_limit: 973
        operational_upper_limit: 3034
        board_name: "arm_bus"
        channel: 1
      }
    }
    single_perceptions {
      node {
        id: 3
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_2_state"
          publish_rate_hz: 30
        }
      }
      sensor {
        sensor_name: "sts3215_encoder_2"
        id: 2
        sensor_type: JOINT_POSITION
        operational_lower_limit: 858
        operational_upper_limit: 3154
        board_name: "arm_bus"
        channel: 2
      }
    }
    single_perceptions {
      node {
        id: 3
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_3_state"
          publish_rate_hz: 30
        }
      }
      sensor {
        sensor_name: "sts3215_encoder_3"
        id: 3
        sensor_type: JOINT_POSITION
        operational_lower_limit: 798
        operational_upper_limit: 3015
        board_name: "arm_bus"
        channel: 3
      }
    }
    single_perceptions {
      node {
        id: 3
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_4_state"
          publish_rate_hz: 30
        }
      }
      sensor {
        sensor_name: "sts3215_encoder_4"
        id: 4
        sensor_type: JOINT_POSITION
        operational_lower_limit: 640
        operational_upper_limit: 3124
        board_name: "arm_bus"
        channel: 4
      }
    }
    single_perceptions {
      node {
        id: 3
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_5_state"
          publish_rate_hz: 30
        }
      }
      sensor {
        sensor_name: "sts3215_encoder_5"
        id: 5
        sensor_type: JOINT_POSITION
        operational_lower_limit: 902
        operational_upper_limit: 2955
        board_name: "arm_bus"
        channel: 5
      }
    }
    single_perceptions {
      node {
        id: 3
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_6_state"
          publish_rate_hz: 30
        }
      }
      sensor {
        sensor_name: "sts3215_encoder_6"
        id: 6
        sensor_type: JOINT_POSITION
        operational_lower_limit: 1795
        operational_upper_limit: 3235
        board_name: "arm_bus"
        channel: 6
      }
    }
  }
}

ai {
  models {
    single_models {
      model_type: SMOLVLA
      # Specify the path to your pretrained SmolVLA model checkpoint
      # Example: "/home/user/.cache/huggingface/hub/models--lerobot--smolvla_base"
      pretrained_model_hf_path: "lerobot/smolvla_base"
      pretrained_model_local_path: "/home/hmoon/models--lerobot--smolvla_base/snapshots/4d2f2b37fa245361ef1efe6d91ce96b8bd4af511"
      node {
        id: 4
        node_type: INFERENCE
        qos_setting {}
        subscriptions {
          ros2_data_type: IMAGE
          topic: "camera_1"
        }
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts_motor_1/position"
        }
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts_motor_2/position"
        }
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts_motor_3/position"
        }
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts_motor_4/position"
        }
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts_motor_5/position"
        }
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts_motor_6/position"
        }
      }

      smolvla_config {
        model_name: "HuggingFaceM4/SmolVLM-Instruct"
        task_description: "Pick up the black object."
      }
    }
  }
}
