general{
  operation_mode: MODE_TELEOPERATE
  robot_type: ROBOT_TYPE_MANIPULATOR_ARM
  name: "so100"
  id: 1
}
robot {
  boards {
    name: "arm_bus"
    board_type: FEETECH_BUS
    comm {
      comm_type: SERIAL
      transport_type: MESSAGE
      serial_config { port: "/dev/ttyACM0" baudrate: 1000000 }
    }
    channels { index: 1 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 1 } }
    channels { index: 2 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 2 } }
    channels { index: 3 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 3 } }
    channels { index: 4 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 4 } }
    channels { index: 5 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 5 } }
    channels { index: 6 drive: SERVO_BUS_UART signal: SERVO_BUS_REGISTER servo_bus { servo_id: 6 } }
  }
  actions {
    single_actions {
      node {
        id: 1
        node_type: ACTUATOR_SUBSCRIBER
        qos_setting {}
        subscriptions {
          ros2_data_type: FLOAT32
          topic: "sts3215_servo_1/position"
          normalized: false
        }
      }
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts3215_servo_1"
        id: 1
        motor_type: MOTOR_STS3215
        board_name: "arm_bus"
        channel: 1
        physical_lower_limit: 0
        physical_upper_limit: 4095
        operational_lower_limit: 973
        operational_upper_limit: 3034
        sts3215_config {
          servo_id: 1
          move_speed: 3000
          idle_position: 2070
        }
      }
    }
    single_actions {
      node {
        id: 1
        node_type: ACTUATOR_SUBSCRIBER
        qos_setting {}
        subscriptions {
          ros2_data_type: FLOAT32
          topic: "sts3215_servo_2/position"
          normalized: false
        }
      }
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts3215_servo_2"
        id: 2
        motor_type: MOTOR_STS3215
        board_name: "arm_bus"
        channel: 2
        physical_lower_limit: 0
        physical_upper_limit: 4095
        operational_lower_limit: 858
        operational_upper_limit: 3154
        sts3215_config {
          servo_id: 2
          move_speed: 3000
          idle_position: 847
        }
      }
    }
    single_actions {
      node {
        id: 1
        node_type: ACTUATOR_SUBSCRIBER
        qos_setting {}
        subscriptions {
          ros2_data_type: FLOAT32
          topic: "sts3215_servo_3/position"
          normalized: false
        }
      }
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts3215_servo_3"
        id: 3
        motor_type: MOTOR_STS3215
        board_name: "arm_bus"
        channel: 3
        physical_lower_limit: 0
        physical_upper_limit: 4095
        operational_lower_limit: 798
        operational_upper_limit: 3015
        sts3215_config {
          servo_id: 3
          move_speed: 3000
          idle_position: 3011
        }
      }
    }
    single_actions {
      node {
        id: 1
        node_type: ACTUATOR_SUBSCRIBER
        qos_setting {}
        subscriptions {
          ros2_data_type: FLOAT32
          topic: "sts3215_servo_4/position"
          normalized: false
        }
      }
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts3215_servo_4"
        id: 4
        motor_type: MOTOR_STS3215
        board_name: "arm_bus"
        channel: 4
        physical_lower_limit: 0
        physical_upper_limit: 4095
        operational_lower_limit: 640
        operational_upper_limit: 3124
        sts3215_config {
          servo_id: 4
          move_speed: 3000
          idle_position: 655
        }
      }
    }
    single_actions {
      node {
        id: 1
        node_type: ACTUATOR_SUBSCRIBER
        qos_setting {}
        subscriptions {
          ros2_data_type: FLOAT32
          topic: "sts3215_servo_5/position"
          normalized: false
        }
      }
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts3215_servo_5"
        id: 5
        motor_type: MOTOR_STS3215
        board_name: "arm_bus"
        channel: 5
        physical_lower_limit: 0
        physical_upper_limit: 4095
        operational_lower_limit: 902
        operational_upper_limit: 2955
        sts3215_config {
          servo_id: 5
          move_speed: 3000
          idle_position: 1838
        }
      }
    }
    single_actions {
      node {
        id: 1
        node_type: ACTUATOR_SUBSCRIBER
        qos_setting {}
        subscriptions {
          ros2_data_type: FLOAT32
          topic: "sts3215_servo_6/position"
          normalized: false
        }
      }
      action_type: ACTUATOR
      actuator {
        actuator_name: "sts3215_servo_6"
        id: 6
        motor_type: MOTOR_STS3215
        board_name: "arm_bus"
        channel: 6
        physical_lower_limit: 0
        physical_upper_limit: 4095
        operational_lower_limit: 1795
        operational_upper_limit: 3235
        sts3215_config {
          servo_id: 6
          move_speed: 2200
          idle_position: 1806
        }
      }
    }
  }

  perceptions {
    single_perceptions {
      node {
        id: 2
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_1_state"
          publish_rate_hz: 30
        }
      }
      perception_type: ENCODER
      encoder {
        encoder_name: "sts3215_encoder_1"
        id: 1
        encoder_type: STS3215_ENCODER
        operational_lower_limit: 1147
        operational_upper_limit: 3154
        sts3215_encoder_config {
          servo_id: 1
        }
      }
    }
    single_perceptions {
      node {
        id: 2
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_2_state"
          publish_rate_hz: 30
        }
      }
      perception_type: ENCODER
      encoder {
        encoder_name: "sts3215_encoder_2"
        id: 2
        encoder_type: STS3215_ENCODER
        operational_lower_limit: 1670
        operational_upper_limit: 3986
        sts3215_encoder_config {
          servo_id: 2

        }
      }
    }
    single_perceptions {
        node {
        id: 2
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_3_state"
          publish_rate_hz: 30
        }
      }
      perception_type: ENCODER
      encoder {
        encoder_name: "sts3215_encoder_3"
        id: 3
        encoder_type: STS3215_ENCODER
        operational_lower_limit: 910
        operational_upper_limit: 3113
        sts3215_encoder_config {
          servo_id: 3

        }
      }
    }
    single_perceptions {
      node {
        id: 2
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_4_state"
          publish_rate_hz: 30
        }
      }
      perception_type: ENCODER
      encoder {
        encoder_name: "sts3215_encoder_4"
        id: 4
        encoder_type: STS3215_ENCODER
        operational_lower_limit: 20
        operational_upper_limit: 2407
        sts3215_encoder_config {
          servo_id: 4

        }
      }
    }
    single_perceptions {
      node {
        id: 2
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_5_state"
          publish_rate_hz: 30
        }
      }
      perception_type: ENCODER
      encoder {
        encoder_name: "sts3215_encoder_5"
        id: 5
        encoder_type: STS3215_ENCODER
        operational_lower_limit: 1730
        operational_upper_limit: 3811
        sts3215_encoder_config {
          servo_id: 5
        }
      }
    }
    single_perceptions {
      node {
        id: 2
        node_type: ENCODER_PUBLISHER
        qos_setting {}
        publishers {
          ros2_data_type: FLOAT32
          topic: "sts3215_encoder_6_state"
          publish_rate_hz: 30
        }
      }
      perception_type: ENCODER
      encoder {
        encoder_name: "sts3215_encoder_6"
        id: 6
        encoder_type: STS3215_ENCODER
        operational_lower_limit: 2028
        operational_upper_limit: 3100
        sts3215_encoder_config {
          servo_id: 6
        }
      }
    }
  }
}
